
#打印sql语句
mybatis.configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8886
  servlet:
    context-path: /

file:
  image-path: /myimages

spring:
  resources: # 指定静态资源的路径
    static-locations: classpath:/static/,classpath:/templates/,classpath:/layui/,file:${file.image-path}
  datasource:
    #服务器数据库
    url: jdbc:mysql:///demo_sl2.2?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource